apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordbot-deployment
spec:
  selector:
    matchLabels:
      app: discordbot
  template:
    metadata:
      labels:
        app: discordbot
    spec:
      containers:
      - name: discordbot
        image: discordbot
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: discordbot-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080