apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-configmap
  namespace: nathan-namespace
  labels:
    app: discordbot
data:
    bot_prefix: '!gobot'
    postgres_port: '5432'
    database_name: postgres