name: Go
# Run on PR creation against main and merge into main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    # Creates postgres from docker for testing
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        # Maps docker port
        ports:
          - 5432:5432

    permissions:
      contents: read
    # Checkout repo
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Go setup using same version project was written in
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    # Lint Go using golanfci linter 
    - name: Golang Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.59
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    # Lints dockerfile using hadolint
    - name: Docker Lint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./Dockerfile
    
    # Builds Go project
    - name: Build
      run: go build -v ./...

    # Runs tests in ./bot directory 
    - name: Test Bot Functionality
      run: go test -v ./bot
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        DATABASE_NAME: ${{ secrets.POSTGRES_DB }}
    
    # Runs tests in ./bot/commands directory
    - name: Test Bot Commands
      run: go test -v ./bot/commands
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        DATABASE_NAME: ${{ secrets.POSTGRES_DB }}